perf(runtime-vapor): optimize `setDOMProp` on static tag + key
vuejs/vue-vapor pull request #294
Opened 2024-11-29 08:41 UTC by edison1105

WIP

2024-11-29 10:11 UTC, edison1105 commented on packages/runtime-vapor/src/dom/prop.ts
> -    // TODO special checks
this special check seems no longer necessary

2024-12-01 02:30 UTC, yyx990803 requested changes

2024-12-01 02:30 UTC, yyx990803 commented on packages/compiler-vapor/__tests__/transforms/__snapshots__/vBind.spec.ts.snap
> +  _renderEffect(() => _setAttr(n0, "innerHTML", _ctx.foo, true))
Only `setStyle` and `setClass` needs the finally `root: true` argument due to possible fallthrough attributes - all other helpers should not include this `true` argument.

2024-12-01 04:04 UTC, yyx990803 approved these changes

2024-12-01 08:50 UTC, LittleSound approved these changes

2024-12-01 09:04 UTC, merged